//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryExplorer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Z { get; set; }
        public bool NorthAllowed { get; set; }
        public bool EastAllowed { get; set; }
        public bool SouthAllowed { get; set; }
        public bool WestAllowed { get; set; }
        public bool UpAllowed { get; set; }
        public bool DownAllowed { get; set; }
        public int RegionId { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
