CREATE TABLE [dbo].[Region]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL, 
    [Description] VARCHAR(MAX) NOT NULL, 
    [OwnerId] INT NOT NULL, 
    [Created] DATETIME NOT NULL DEFAULT GETDATE()
)
